//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1059 with alias "summaryInfo"
	/// <summary>Summary Info</summary>
	public partial interface ISummaryInfo : IPublishedContent
	{
		/// <summary>Summary Image</summary>
		IPublishedContent SummaryImage { get; }

		/// <summary>Summary Text</summary>
		string SummaryText { get; }
	}

	/// <summary>Summary Info</summary>
	[PublishedContentModel("summaryInfo")]
	public partial class SummaryInfo : PublishedContentModel, ISummaryInfo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "summaryInfo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SummaryInfo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SummaryInfo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Summary Image
		///</summary>
		[ImplementPropertyType("summaryImage")]
		public IPublishedContent SummaryImage
		{
			get { return GetSummaryImage(this); }
		}

		/// <summary>Static getter for Summary Image</summary>
		public static IPublishedContent GetSummaryImage(ISummaryInfo that) { return that.GetPropertyValue<IPublishedContent>("summaryImage"); }

		///<summary>
		/// Summary Text
		///</summary>
		[ImplementPropertyType("summaryText")]
		public string SummaryText
		{
			get { return GetSummaryText(this); }
		}

		/// <summary>Static getter for Summary Text</summary>
		public static string GetSummaryText(ISummaryInfo that) { return that.GetPropertyValue<string>("summaryText"); }
	}
}
