//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1060 with alias "taxonomy"
	/// <summary>Taxonomy</summary>
	public partial interface ITaxonomy : IPublishedContent
	{
		/// <summary>Category</summary>
		IEnumerable<string> Category { get; }

		/// <summary>Tags</summary>
		IEnumerable<string> Tags { get; }
	}

	/// <summary>Taxonomy</summary>
	[PublishedContentModel("taxonomy")]
	public partial class Taxonomy : PublishedContentModel, ITaxonomy
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "taxonomy";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Taxonomy(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Taxonomy, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public IEnumerable<string> Category
		{
			get { return GetCategory(this); }
		}

		/// <summary>Static getter for Category</summary>
		public static IEnumerable<string> GetCategory(ITaxonomy that) { return that.GetPropertyValue<IEnumerable<string>>("category"); }

		///<summary>
		/// Tags
		///</summary>
		[ImplementPropertyType("tags")]
		public IEnumerable<string> Tags
		{
			get { return GetTags(this); }
		}

		/// <summary>Static getter for Tags</summary>
		public static IEnumerable<string> GetTags(ITaxonomy that) { return that.GetPropertyValue<IEnumerable<string>>("tags"); }
	}
}
